package com.example.imitatejingdong.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.imitatejingdong.bean.SeekBean;

import com.example.imitatejingdong.greenDao.SeekBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig seekBeanDaoConfig;

    private final SeekBeanDao seekBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        seekBeanDaoConfig = daoConfigMap.get(SeekBeanDao.class).clone();
        seekBeanDaoConfig.initIdentityScope(type);

        seekBeanDao = new SeekBeanDao(seekBeanDaoConfig, this);

        registerDao(SeekBean.class, seekBeanDao);
    }
    
    public void clear() {
        seekBeanDaoConfig.clearIdentityScope();
    }

    public SeekBeanDao getSeekBeanDao() {
        return seekBeanDao;
    }

}
